# Entrada de datos  : input()
print('-' * 80)
print('Entrada de datos : input()')
print()

_user_code = input("_user_code = input('Código : ')          = ")
user_name = input("user_name = input('Nombre : ')           = ")
user_lastname = input("user_lastname = input('Apellido : ')     = ")
user_age = input("user_age = input('Edad : ')              = ")
user_height = input("user_height = input('Estatura : ')       = ")
blood_group = input("blood_group = input('Grp sang : ')       = ")
blood_type = input("blood_type = input('Tip sang : ')        = ")
print()
print("     print(_user_code)       = ", _user_code)
print("     print(user_name)        = ", user_name)
print("     print(user_lastname)    = ", user_lastname)
print("     print(user_age)         = ", user_age)
print("     print(user_height)      = ", user_height)
print("     print(blood_group)      = ", blood_group)
print("     print(blood_type)       = ", blood_type)
print()
print('-' * 80)
print()