print()
# Funciones
print("Funciones Globales")
print()
# type()
print("Tipo de dato: type()")
print("     print(type(1)) =", type(1))
# int()
print("Conversión a un entero: int()")
un_entero = int('5')
print("     un_entero = int('5')")
print("     print(un_entero) =", un_entero)
print("     print(type(un_entero)) =", type(un_entero))
# bool()
print("Conversión a booleano: bool()")
a = bool('a')
print("     a = bool('a')")
print("     print(a) =", a)
print("     print(type(a)) =", type(a))
a = bool('')
print("     a = bool('')")
print("     print(a) =", a)
print("     print(type(a)) =", type(a))
# float()
print("Conversión a Decimal: float()")
a = float(3)
print("     a = float(3)")
print("     print(a) =", a)
print("     print(type(a)) =", type(a))
print()