print()
# Funciones
print("Funciones Globales")
print()
# type()
print("Tipo de dato: type()")
print("     print(type(1)) =", type(1))
# int()
print("Conversión a un entero: int()")
un_entero = int('5')
print("     un_entero = int('5')")
print("     print(un_entero) =", un_entero)
print("     print(type(un_entero)) =", type(un_entero))
# bool()
print("Conversión a booleano: bool()")
a = bool('a')
print("     a = bool('a')")
print("     print(a) =", a)
print("     print(type(a)) =", type(a))
a = bool('')
print("     a = bool('')")
print("     print(a) =", a)
print("     print(type(a)) =", type(a))
# float()
print("Conversión a Decimal: float()")
a = float(3)
print("     a = float(3)")
print("     print(a) =", a)
print("     print(type(a)) =", type(a))
print()
# Definir una función
print("Definir una función")
def suma_de_dos_numeros(x, y):
    return x + y
print("     def suma_de_dos_numeros(x,y):")
print("         return x + y")
print()
print()
print("     suma_de_dos_numeros(10, 15) =", suma_de_dos_numeros(10, 15))
print("     print(type(suma_de_dos_numeros)) =", type(suma_de_dos_numeros))
print()
# Asignar valor de función a una variable
print("Asignar valor de una función a una variable")
suma_total = suma_de_dos_numeros(10, 15)
print("     suma_total = suma_de_dos_numeros(10, 15)")
print("     print(suma_total) =", suma_total)
print("     print(type(suma_total)) =", type(suma_total))
print()